### ISSUE TITLE
Versión vagrant & virtualbox ?

### ISSUE THREAD

**Issue by JavierMoralesEstevez** [OmniLayer/omni-devops#9]
can you tell me what version of vagrant and virtual box works ?
thanks you

**Comment by msgilligan** [comment]
The README says:

* Virtual Box 4.3.10 or later
* Vagrant 1.6.2 or later

But realize there have been significant changes to Omni and no updates to this repo for over 3 years. See Issue #10. 

I'm going to close this bug as effectively a duplicate of #10.
